### PR TITLE
Fix path-based dependencies in sub-packages from path-based dependencies

### LINKED ISSUE #2587: v1.30.0 dependency resolution regression with subpackages in dependency
Reproduction:

```json
// a/dub.json
{
        "name": "a",
        "dependencies": {
                "b": {"path":"../b"}
        }
}
```

```json
// b/dub.json
{
        "name": "b",
        "dependencies": {
                "b:sub":"*"
        },
        "subPackages": [
                {
                        "name": "sub",
                        "dependencies": {
                                "c": {"path":"../c"}
                        }
                }
        ]
}
```

```json
// c/dub.json
{
        "name": "c"
}
```

In b the subpackage can be embedded in the recipe or standalone, it doesn't matter for the upgrade bug.

Trying to run `dub upgrade` in `a` causes

```
Error Unresolvable dependencies to package c:
  b:sub @/tmp/repr/b depends on c @/tmp/repr/c
```

Worked with 1.29.2 and before.

### PR DESCRIPTION
**Pull request by WebFreak001**
Fix #2587

### CODE REVIEW

File: source/dub/dub.d [hunk 1]
```diff
@@ -864,7 +864,7 @@ class Dub {
 		if (options & FetchOptions.printOnly) {
 			if (existing && existing.version_ != ver)
 				logInfo("A new version for %s is available (%s -> %s). Run \"%s\" to switch.",
-					packageId.color(Mode.bold), existing.version_, ver,
+					packageId.color(Mode.bold), existing, ver,
```
Comment (WebFreak001) [inline source/dub/dub.d:867]: version_ crashes with non-version-range dependency specifications, so for logging we just dump the Dependency directly

**Comment by ibuclaw** [comment]
Does windows always fail?

**Comment by WebFreak001** [comment]
yes

**Comment by ibuclaw** [comment]
Is anything going to be done about it?  I'd hate to promote normalizing the behaviour of ignoring test results.

**Comment by WebFreak001** [comment]
I'll try starting by first just using a smaller cache string (e.g. replace the long sha string with a truncated base64 one) in a separate PR

**Review by ibuclaw — APPROVED** [review]

**Comment by ibuclaw** [comment]
Merging for now, so can get on with tagging beta for point release.  If there's still any issues, there's a few days to fix them.

File: source/dub/dub.d [hunk 2]
```diff
@@ -1631,7 +1631,7 @@ private class DependencyVersionResolver : DependencyResolver!(Dependency, Depend
 	protected override Dependency[] getSpecificConfigs(string pack, TreeNodes nodes)
 	{
 		if (!nodes.configs.path.empty || !nodes.configs.repository.empty) {
-			if (getPackage(pack, nodes.configs)) return [nodes.configs];
+			if (getPackage(nodes.pack, nodes.configs)) return [nodes.configs];
```
Comment (Geod24) [inline source/dub/dub.d:1634]: Duh, glad to see it was a dumb typo in the end.

Comment (WebFreak001) [reply source/dub/dub.d:1634]: yeah, no idea how the hashOf removal broke this though, can only guess that it was missing checks further inside, because path based dependencies used to always equal to true whenever comparing with any other path based dependencies.
