### PR TITLE
Use queryString to setup the pacakge parameters

### LINKED ISSUE #1907: Exception on fetching packages because `?` is escaped
Linux with latest dub compiled with vibe-core so `Have_vibe_core` version is set

Build `dub` with `Have_vibe_core` (I am using the latest vibe release) and force it to  fetch a new package. A new exception is raised because the `?` char from the url is escaped.

It looks like vibe changed the `NativePath` implementation. 

```
Downloading metadata for mir-linux-kernel
[main(----) dbg] Error while handling response: vibe.http.common.HTTPStatusException@../../.dub/packages/vibe-d-0.8.6/vibe-d/inet/vibe/inet/urltransfer.d(62): Server responded with Not Found for https://code.dlang.org/api/packages/infos%3Fpackages=%5B%22mir-linux-kernel%22%5D&include_dependencies=true&minimize=true
[main(----) dbg] ----------------
[main(----) dbg] ../../.dub/packages/vibe-d-0.8.6/vibe-d/inet/vibe/inet/urltransfer.d:62 void vibe.inet.urltransfer.download!(void*).download(vibe.inet.url.URL, void delegate(scope vibe.core.stream.InputStream), void*).__lambda6(scope vibe.http.client.HTTPClientResponse) [0xe56af1]
[main(----) dbg] ../../.dub/packages/vibe-d-0.8.6/vibe-d/http/vibe/http/client.d:560 @trusted void vibe.http.client.HTTPClient.request(scope void delegate(scope vibe.http.client.HTTPClientRequest), scope void delegate(scope vibe.http.client.HTTPClientResponse)) [0xef629f]
[main(----) dbg] ../../.dub/packages/vibe-d-0.8.6/vibe-d/inet/vibe/inet/urltransfer.d:52 @safe void vibe.inet.urltransfer.download!(void*).download(vibe.inet.url.URL, void delegate(scope vibe.core.stream.InputStream), void*) [0xe56866]
[main(----) dbg] ../../.dub/packages/vibe-d-0.8.6/vibe-d/inet/vibe/inet/urltransfer.d:99 @safe void vibe.inet.urltransfer.download!(void*).download(immutable(char)[], scope void delegate(scope vibe.core.stream.InputStream), void*) [0xe565e1]
[main(----) dbg] ../dub/source/dub/internal/utils.d:274 ubyte[] dub.internal.utils.download(immutable(char)[], uint) [0xe53d31]
[main(----) dbg] ../dub/source/dub/internal/utils.d:281 ubyte[] dub.internal.utils.download(vibe.inet.url.URL, uint) [0xe372fe]
[main(----) dbg] ../dub/source/dub/internal/utils.d:364 ubyte[] dub.internal.utils.retryDownload(vibe.inet.url.URL, ulong, uint) [0xddb708]
[main(----) dbg] ../dub/source/dub/packagesuppliers/registry.d:95 vibe.data.json.Json dub.packagesuppliers.registry.RegistryPackageSupplier.getMetadata(immutable(char)[]) [0xd1ddb6]
[main(----) dbg] ../dub/source/dub/packagesuppliers/registry.d:38 dub.dependency.Version[] dub.packagesuppliers.registry.RegistryPackageSupplier.getVersions(immutable(char)[]) [0xd1d5cf]
[main(----) dbg] /usr/include/dmd/phobos/std/typecons.d-mixin-4570:4584 dub.dependency.Version[] std.typecons.AutoImplement!(dub.packagesuppliers.fallback.AbstractFallbackPackageSupplier, dub.packagesuppliers.fallback.fallback, std.traits.isAbstractFunction).AutoImplement.getVersions(immutable(char)[]) [0xd54c5c]
[main(----) dbg] ../dub/source/dub/dub.d:488 void dub.dub.Dub.upgrade(dub.dub.UpgradeOptions, immutable(char)[][]) [0xcd070c]
[main(----) dbg] ../dub/source/dub/commandline.d:1046 void 
...
```

### PR DESCRIPTION
**Pull request by gedaiu**
fix #1907

### CODE REVIEW

File: source/dub/packagesuppliers/registry.d [hunk 1]
```diff
@@ -86,8 +86,10 @@ class RegistryPackageSupplier : PackageSupplier {
 			m_metadataCache.remove(packageId);
 		}
 
-		auto url = m_registryUrl ~ NativePath("api/packages/infos?packages=[\"" ~
-				packageId ~ "\"]&include_dependencies=true&minimize=true");
+		auto url = m_registryUrl ~ NativePath("api/packages/infos");
+
+		url.queryString = "packages=[\"" ~
+				packageId ~ "\"]&include_dependencies=true&minimize=true";
```
Comment (WebFreak001) [inline source/dub/packagesuppliers/registry.d:92]: `packageId` doesn't really look like it would be escaped from the caller (like `fetchPackageRecipe(packageId, ...)` -> `getMetadata(packageId)`) so this could suffer from issues like having `&` in the packageId or manipulating the other arguments. Can you uri component escape the packageId?

Comment (gedaiu) [reply source/dub/packagesuppliers/registry.d:92]: if this is the case, would this function solve the issue? https://dlang.org/phobos/std_uri.html#.encodeComponent

Comment (WebFreak001) [reply source/dub/packagesuppliers/registry.d:92]: yes that would be a good solution

Comment (gedaiu) [reply source/dub/packagesuppliers/registry.d]: done

**Comment by gedaiu** [comment]
what does this pr need to be merged?

**Comment by thewilsonator** [comment]
It needs to pass the CI. If you think it already should, force push.

**Comment by gedaiu** [comment]
@thewilsonator how can I find why the travis build failed? I get an `There was an error while trying to fetch the log.` error when I want to check the logs...

**Comment by WebFreak001** [comment]
I think that's an issue with travis right now, I tried restarting the build but it's still failing to get the log

**Comment by PetarKirov** [comment]
I have a suspicion about the problem with Travis CI. I'll try to debug it in #1920.

**Comment by PetarKirov** [comment]
With #1920 merged, this PR is finally green on Travis.

@gedaiu two suggestions before we merge:
1. Is possible to add an integration test (look here for inspiration: https://github.com/dlang/dub/tree/master/test) to verify that your fix is correct and to ensure it doesn't break in future?
2. After your done, can you squash your commits?

**Comment by gedaiu** [comment]
Thanks @PetarKirov 

I squashed the commits. This change should be already covered by some bash scripts. I am not sure how I should write a new one, since the build that is tested is not using vibe as a dependency, which caused my error.

**Comment by WebFreak001** [comment]
travis should probably be extended to run the tests also using vibe

**Comment by gedaiu** [comment]
@PetarKirov @WebFreak001 I won't do this in this PR. I think this is a subject for another PR.

**Comment by WebFreak001** [comment]
fair enough, looks like a stable change with existing issue for this anyway

**Comment by PetarKirov** [comment]
@gedaiu Thanks for your work! Yeah, it's fine to addressed the suggestions in a separate PR.

**Comment by gedaiu** [comment]
Thanks for the review, too!
