### PR TITLE
Cache json db

### LINKED ISSUE #2640: Dub support in Meson is broken
Change #2589 has broken Meson support for Dub packages.
Meson will not try to build Dub packages directly but rely instead on the Dub cache to find a package built by Dub.
The way it is done is to find the relevant info in the cache dir name.
For example `library-debug-linux.posix-x86_64-ldc_2081-EF934983A3319F8F8FF2F0E107A363BA`.
Now in the new shorter cache dir name, it is not possible anymore.

If short names are that important, can I suggest that the dir names is composed of two hashes:
 1. one hash that contains infos meson needs and that can be reliably computed by meson as well
    a. compiler
    b. compiler version
    c. arch
    d. platform
 2. a second hash for all info dub needs and meson has no clue about

E.g.
```
library-debug-bUZ3sLErP9iQlvgdxNNYQg
```
would become
```
library-debug-xXxXx-yYyYyYyYyYyYyYyYyYyYyY
              ~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
                1            2
```
5 chars in base64 is more than a billion possibilities. Even if not perfectly distributed, it is more than enough to prevent accidental collisions.

### PR DESCRIPTION
**Pull request by rtbo**
As discussed in #2640, proposal to write Json files in the cache for 3rd party software like Meson to assess compatibility of artifacts in the Dub cache.
I've made the choice to write small Json files per package version rather than a gigantic one for the whole cache.
This comes at the price of stabilizing the directory structure within the cache (up to where the json file is written).

The PR add the following files in the cache
```
~/.dub/cache/vibe-d/0.9.6/+http/build-db.json
~/.dub/cache/vibe-d/0.9.6/+http/build-db.lock
```
To ensure interoperability, the following stabilization apply:
```
~/.dub/cache/vibe-d/0.9.6/+http/build-db.json
~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1             2
```
1. `$DUB_HOME/cache` _default_ location is stable (env-vars and settings customization still apply)
2. Json file path relative to `$DUB_HOME/cache` is stable

The final artifact location remains up to Dub developers.

fixes #2640

### CODE REVIEW

**Comment by WebFreak001** [comment]
since you want to ensure that the output doesn't change, do you want to add a test in the tests folder that checks the file to match exactly using `diff`?

File: source/dub/generators/build.d [hunk 1]
```diff
@@ -285,12 +285,59 @@ class BuildGenerator : ProjectGenerator {
...
+		entry["buildType"] = settings.buildType;
+		entry["compiler"] = settings.platform.compiler;
+		entry["compilerVersion"] = settings.platform.compilerVersion;
+		entry["compilerBinary"] = settings.platform.compilerBinary;
+		entry["architecture"] = serializeToJson(settings.platform.architecture);
+		entry["platform"] = serializeToJson(settings.platform.platform);
+		entry["buildId"] = build_id;
+		entry["targetBinaryPath"] = target_binary_path;
+
+		db ~= entry;
```
Comment (WebFreak001) [inline source/dub/generators/build.d:336]: this seems to grow infinitely / doesn't check for duplicates. E.g. when you build with `--force`, it will add duplicate entries.

**Review by WebFreak001 — CHANGES_REQUESTED** [review]

**Comment by rtbo** [comment]
> since you want to ensure that the output doesn't change, do you want to add a test in the tests folder that checks the file to match exactly using `diff`?

The Json file contains the build ID, which varies with compiler version. So I can't predict in a test what the exact content is.
At best I can check if all the Json fields are there and the value of the immutable ones.

File: source/dub/generators/build.d [hunk 2]
```diff
@@ -285,12 +285,68 @@ class BuildGenerator : ProjectGenerator {
...
+		if (exists(dbPathStr)) {
+			const text = stripUTF8Bom(cast(string)readFile(dbPath));
+			db = parseJsonString(text, dbPathStr);
+			enforce(db.type == Json.Type.array, "Expected a JSON array in " ~ dbPathStr);
+		}
+		else {
+			db = Json.emptyArray;
+		}
+
+		foreach (entry; db) {
```
Comment (WebFreak001) [inline source/dub/generators/build.d:324]: maybe this should be a
```suggestion
		foreach_reverse (entry; db) {
```
since latest entries are gonna be at the bottom and it's most likely cache hits are from recent builds

File: test/pr2642-cache-db/source/test_cache_db.d [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+        rmdirRecurse(dubhome);
+    }
+
+    const string[string] env = [
+        "DUB_HOME": dubhome,
+    ];
+    const fetchProgram = [
+        environment["DUB"],
+        "fetch",
+        "vibe-d@0.9.6",
```
Comment (WebFreak001) [inline test/pr2642-cache-db/source/test_cache_db.d:23]: `gitcompatibledubpackage` might be better for build time

**Review by WebFreak001 — APPROVED** [review]

**Comment by WebFreak001** [comment]
thanks, seems to be a well designed and useful feature!

**Comment by rtbo** [comment]
Thanks for the quick review !

**Comment by Geod24** [comment]
I've missed the discussion here, but why are we adding JSON files for other tools to depend on ? `dub describe` was meant as the way to do this, why is it not enough ?

**Comment by Geod24** [comment]
I'm not sure what "stabilization" means in this context, either. The commit just adds comments.

**Comment by rtbo** [comment]
`dub describe` doesn't give any info about cached builds.
e.g. on my system
```
tree ~/.dub/cache/urld
/home/remi/.dub/cache/urld
└── 2.1.1
    ├── build
    │   ├── library-debug-cu9jbmcFOeHiBceMMo2VbA
    │   │   └── liburld.a
    │   └── library-debug-Z7qINYX4IxM8muBSlyNGrw
    │       └── liburld.a
    ├── db.json
    └── db.lock
```
Meson needs to know what these 2 archives are (compiler, compiler version etc.) in order to use them properly.
Meson uses `dub describe` for everything else (import paths, sub-dependencies etc.), but the cache info is not available.
I have to say that enriching `dub describe` output would have been a viable option as well (e.g. add the buildId).

**Comment by rtbo** [comment]
> I'm not sure what "stabilization" means in this context, either. The commit just adds comments.

What is stable is what should not be changed in future Dub versions.

**Comment by Geod24** [comment]
> What is stable is what should not be changed in future Dub versions.

The only thing that should not be changed in future dub version is whatever is part of the API. And the API to access dub's internal data is `dub describe`, hence my comment.
