### PR TITLE
Trivial: Fix #2774  - Color codes on windows terminal

### LINKED ISSUE #2774: `dub init` colors are broken on cmd
### System information

- **dub version**: DUB version 1.35.1, built on Jan  1 2024
- **OS Platform and distribution**: Windows 10 (in VMWare Player, but I doubt that matters)
- **compiler version** dmd-v2.106.1 not that it matters

### Bug Description

The colors are messed up, but what's odd is that it does succeed at coloring the last bit properly

image

### How to reproduce?

Run `dub init` in cmd on a fresh installation of Windows 10

### Expected Behavior

Colors

### PR DESCRIPTION
**Pull request by MrcSnm**

### CODE REVIEW

File: source/dub/commandline.d [hunk 1]
```diff
@@ -1069,7 +1070,7 @@ class InitCommand : Command {
 						 free_choice ? " or enter a custom value" : null);
 			}
 		}
-
+
```
Comment (Geod24) [inline source/dub/commandline.d:1073]:
```suggestion

```
