### PR TITLE
Fix #2141 - When used as a library, the default compiler is different from the expected.

### LINKED ISSUE #2141: When used as a library, the default compiler is different from the expected.
The current dub may not detect the default compiler as intended due to the mechanism of detecting the preferred compiler by thisExePath when used in libraries.
When used as a library, the following code, which assumes that the executable file path and the compiler are located in the same place, will not work:
https://github.com/dlang/dub/blob/4c1ce741d69316093d69721cdf73fc13666d6f83/source/dub/dub.d#L1495

The current determineDefaultCompiler function ignores the environment variable DC. The environment variable DC suggests which compiler should be preferred, as specified in dlang-setup in GitHub Actions or in install.sh.

It also doesn't seem to be a good idea for the compiler type to take precedence over the path priority.
If `PATH=C:\ldc\bin;C:\dmd\bin;%PATH%`, then ldc2 should have priority over dmd.

https://github.com/dlang/dub/blob/4c1ce741d69316093d69721cdf73fc13666d6f83/source/dub/dub.d#L1508

### PR DESCRIPTION
**Pull request by shoo**
If a default compiler is given, eg. DC, the compiler is searched from the paths, and if not, the compiler is searched according to the priority of the paths.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

File: source/dub/dub.d [hunk 1]
```diff
@@ -1502,11 +1502,67 @@ class Dub {
...
+		version (Posix) enum sep = ":", exe = "";
+		
+		immutable dmdpath = testdir.buildPath("dmd", "bin");
+		immutable ldcpath = testdir.buildPath("ldc", "bin");
+		mkdirRecurse(dmdpath);
+		mkdirRecurse(ldcpath);
+		immutable dmdbin = dmdpath.buildPath("dmd"~exe);
+		immutable ldcbin = ldcpath.buildPath("ldc2"~exe);
+		std.file.write(dmdbin, null);
+		std.file.write(ldcbin, null);
```
Comment (Geod24) [inline source/dub/dub.d:1546]: Unittest should not do IO!
