### PR TITLE
Fix #2450 - issue1474 testcase is broken on Windows

### LINKED ISSUE #2450: issue1474 testcase is broken on Windows
### System information
- **dub version**: dub (master branch / commit: https://github.com/dlang/dub/commit/de8925d0346f4ddeb49b4255625b70380b7a8f70)
- **OS Platform and distribution**: Windows 11
- **compiler version**: dmd-2.100.0 / ldc-1.30.0

### Bug Description
test/issue1474 is not work on Windows

This problem occurs only on Windows. The contents of `test/issue1474` test case show that it can be built on Windows.
Some of the commands for generating source files are linux-dependent, but even after rewriting them for Windows, they still do not work.
In short, the wildcard glob expansion does not work properly on Windows.

### How to reproduce?
```
git checkout de8925d0346f4ddeb49b4255625b70380b7a8f70
dub run -- build --root=test/issue1474
```

### Expected Behavior
Successful builds, even on Windows

### Logs
```
> dub run -- build --root=test/issue1474 -v
Performing "debug" build using ......\dmd.exe for x86_64.
dub 1.29.1+commit.268.gde8925d0: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running bin/dub.exe build --root=test/issue1474 -v
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at ......\AppData\Local\dub\packages\local-packages.json
Looking for local package map at ......\dub\test\issue1474\.dub\packages\local-packages.json
Determined package version using GIT: gitcompatibledubpackage 1.0.4+commit.2.gccb31bf
Note: Failed to determine version of package generated-sources at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
Looking for local package map at ......\AppData\Local\dub\packages\local-packages.json
Looking for local package map at ......\dub\test\issue1474\.dub\packages\local-packages.json
Generating using build
     Pre-gen Running commands for generated-sources
Running echo 'extern(C) int fun42 () { return 42; }' > ext/fortytwo.d
Configuring dependent generated-sources, deps:
    Starting Performing "debug" build using dmd for x86_64.
Target '......\dub\test\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\generated-sources.exe' doesn't exist, need rebuild.
    Building generated-sources ~master: building configuration [application]
dmd -m64 -c -oftest\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\generated-sources.obj -debug -g -w -version=Have_generated_sources -Itest\issue1474\source test\issue1474\source\app.d -vcolumns
     Linking generated-sources
dmd -oftest\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\generated-sources.exe test\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\generated-sources.obj -m64 -g
generated-sources.obj : error LNK2019: 未解決の外部シンボル fun42 が関数 _Dmain で参照されました。
generated-sources.obj : error LNK2019: 未解決の外部シンボル funkekw が関数 _Dmain で参照されました。
test\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\generated-sources.exe : fatal error LNK1120: 2 件の未解決の外部参照
Error: linker exited with status 1120
FAIL test\issue1474\.dub\build\application-debug-windows-x86_64-dmd_v2.100.1-6A5CB634D7D71D5FA4498FBD6F921282747EA1769A71CA7A27B240B2599C8C66\ generated-sources executable
Error dmd failed with exit code 1.
Program exited with code 2
```
Logs have been partially processed.

### PR DESCRIPTION
**Pull request by shoo**

### CODE REVIEW

File: source/dub/project.d [hunk 1]
```diff
@@ -1421,6 +1421,7 @@ private string[] processVarsWithGlob(Project, Package)(string var, in Project pr
 		{
 		case '*', '?', '[', '{': break loop;
 		case '/': sepIdx = i; goto default;
```
Comment (tom-tan) [inline source/dub/project.d:1423]: Does `/` work as a separator on Windows?
If not, we need `version(Posix)` for this case statement.

Comment (rikkimax) [reply source/dub/project.d:1423]: Yes, but it may depend upon UNC library.

https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalize-separators

Comment (shoo) [reply source/dub/project.d:1423]: In Windows, both `/` and `\` function as path separators.
In fact, it is already converted to `\` by NativePath.toNativeString in the previous processVars, but it is better to work more robustly.

**Review by Geod24 — APPROVED** [review]
